### ISSUE TITLE
Won't start because of locale issues

### ISSUE THREAD

**Issue by eelfroth** [fagga/transmission-remote-cli#168]
```

user@hostname ~> transmission-remote-cli 
Traceback (most recent call last):
  File "/usr/bin/transmission-remote-cli", line 74, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

user@hostname ~> locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

```

**Comment by eelfroth** [comment]
actually, this seems to be the same as [Issue #72](https://github.com/fagga/transmission-remote-cli/issues/72) and I should stop whining and fix my configs.
